### ISSUE TITLE
Missing dependencies?

### ISSUE THREAD

**Issue by diodenschein** [inventree/inventree-brother-plugin#18]
Hello I managed to get this installed and running. It's great!

There are a few missing dependencies though. 
I have no idea how they would get installed in the inventree install process but:

apt install build-essential libpoppler-cpp-dev pkg-config poppler-utils
pip install pdf-info python-poppler 

Was what I needed.

**Comment by matmair** [comment]
Hi there @diodenschein 
We can not easily add debian requirements to the pip package but we can include the info in the docs. thanks for the report.
