### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by sebpwhite** [inventree/inventree-brother-plugin#20]
Hi. I'm probably missing something obvious but I can't figure out why this plugin won't install for me.
I installed Inventree into a Debian 11 LXC container (hosted on Proxmox) using the install script. The Inventree install itself went fine.
I attempted to install using the `pip install inventree-brother-plugin`. No errors or warnings and `pip show inventree-brother-plugin` yields:

`root@ct-inventree:/etc/inventree# pip show inventree-brother-plugin
Name: inventree-brother-plugin
Version: 0.6.0
Summary: Brother label printer plugin for InvenTree
Home-page: https://github.com/inventree/inventree-brother-plugin
Author: Oliver Walters
Author-email: oliver.henry.walters@gmail.com
License: MIT
Location: /usr/local/lib/python3.9/dist-packages
Requires: brother-ql-inventree
Required-by:`

However I don't see an entry for the plugin in the web interface and nothing in the admin side either.

Any ideas on what I'm missing here?

**Comment by sebpwhite** [comment]
Screenshots of what I see in the web interface in case it helps! Also, I have rebooted the system several times since running the pip install command.
<img width="1378" alt="image" src="https://github.com/inventree/inventree-brother-plugin/assets/6755837/b38e6fc2-6874-4776-9e51-77327c8db28c">
<img width="1445" alt="image" src="https://github.com/inventree/inventree-brother-plugin/assets/6755837/5d2abcb3-5790-429d-9851-a7f2878e2cc3">

**Comment by SchrodingersGat** [comment]
If you are running within a container you will probably want to enable this option:

![image](https://github.com/inventree/inventree-brother-plugin/assets/10080325/ab334079-6d63-4436-bbf2-350baebfebe9)

And then restart the container service

**Comment by sebpwhite** [comment]
Thanks very much for the quick reply. Unfortunately enabling that option doesn't seem to make a difference. I still don't see the plugin in admin or the settings section after enabling that option and rebooting. `pip show` still lists it as installed. Is there anything else I need to do to make Inventree see the plugin that was installed. The documentation says plugins should be in `/opt/inventree/Inventree/plugins` but pip installed the package to `/usr/local/lib/python3.9/dist-packages`. Is that part of the problem?

**Comment by matmair** [comment]
@sebpwhite what install instructions did you follow?
A possible solution would be to install the plugin again from InvenTree global settings - could be that it currently is installed in the wrong python venv.

**Comment by sebpwhite** [comment]
Thanks for the reply @matmair .
I just looked at the main [readme.md file](https://github.com/inventree/inventree-brother-plugin/blob/main/README.md). In the same Debian 11 LXC that I ran the install script for inventree I ran `pip install inventree-brother-plugin` to install the plugin. Also installed the 2 lots dependencies listed there.

I did notice the option to install via the web ui. What url should I put in the 'Source URL' field there? I tried `https://github.com/inventree/inventree-brother-plugin.git` and I got green banner message saying 'Plugin Installed' but it still doesn't appear after a reboot.

I'm not very experienced with python venvs. I had a quick look at the official install.sh script I used to install inventree and I can't see any hints as to what venv is created there so I'm not too sure where to start making sure I'm running pip in the right environment.

**Comment by matmair** [comment]
@sebpwhite you can just use the package name, no need for source URL in this case.

**Comment by sebpwhite** [comment]
I ended up figuring it out through the command line.
First running `source /opt/inventree/env/bin/activate` to get into the right venv before running the `pip install inventree-brother-plugin` did the trick. Thanks very much for pointing me in the right direction @matmair !
