### ISSUE TITLE
Multiple printer support

### ISSUE THREAD

**Issue by Tomaaso** [inventree/inventree-brother-plugin#28]
Hi,

I have installed a Brother QL-820NWB printer on my Inventree system, and it is working quite well. In the future, my team and I are considering acquiring multiple printers for various label formats and different locations within our lab.
Do you know if this is supported? 

Plugin Version: 0.7.2
Inventree Version: 0.12.6

Thank you.

**Comment by SchrodingersGat** [comment]
this is not supported yet - would require some changes to the InvenTree code. There have been some discussions to this point but nothing has been implement yet:

- https://github.com/inventree/InvenTree/issues/4789
- https://github.com/inventree/InvenTree/pull/4824

**Comment by SchrodingersGat** [comment]
Update: This PR to the core InvenTree code base may provide a solution: https://github.com/inventree/InvenTree/pull/5786

**Comment by wolflu05** [comment]
This is not the main intention for printing options, I still want to implement the machines, and I now plan to push the machine integration forward. Printing options were already a thing I need for the machine registry.

**Comment by matmair** [comment]
This would probably be enabled by addressing https://github.com/inventree/inventree-brother-plugin/issues/32

**Comment by simonkuehling** [comment]
@Tomaaso version 1.0.0 of the plugin now supports InvenTree's machine registry and can be used to set up multiple different label printers all at the same time 👍

I guess this can be closed then?
