### ISSUE TITLE
USB printer support

### ISSUE THREAD

**Issue by timmyhadwen** [inventree/inventree-brother-plugin#29]
Currently this plugin only supports networked printers however the brother_ql library supports USB printers as well. I have tested this by changing the send_label function.

**Comment by SchrodingersGat** [comment]
@timmyhadwen interesting, would you be able to submit a PR to provide USB functionality?

**Comment by timmyhadwen** [comment]
I have a fork with just hardcoded values for device address etc. More than happy to complete that implementation with settings etc however just struggling to get the plugin installed in a development environment? Do you have any tips for easy dev of plugins etc? I am currently using Docker and have the plugin cloned into the plugins folder but alas it won't install properly and can't see a nice way to get logs out. Any help or pointing in the right direction would be great :)

**Comment by SchrodingersGat** [comment]
If you have the plugin cloned directly into the external "plugins" directory, it won't detect and load, as it is buried too "deep" in the directory structure.

Put the `invenrtee_brother` subdirectory into the "plugins" directory, and then it should load. Can you check if this works for you?

**Comment by wolflu05** [comment]
The easiest thing for me is using devcontainers in combination with editable installs. I described them on the docs a while ago: https://docs.inventree.org/en/stable/develop/devcontainer/?h=devcont#plugin-development

**Comment by SchrodingersGat** [comment]
@timmyhadwen did you get it working?

**Comment by timmyhadwen** [comment]
Thanks for your help guys. Work has been busy but hoping to get into a few PRs over the Christmas break. Will update soon.

**Comment by RealNagus** [comment]
Hello. I needed the USB connection as well and implemented an additional setting for the plugin. Seems to work fine. You find the changes in my fork, if you're still interested I can create a PR.

**Comment by SchrodingersGat** [comment]
@RealNagus a PR would be greatly appreciated!
