### ISSUE TITLE
[FR] Print multiple copies of a label

### ISSUE THREAD

**Issue by Alex9779** [inventree/inventree-brother-plugin#30]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

I started using InvenTree a few weeks ago and use a Brother label printer now.
I am pretty impressed what InvenTree does and how it helps me now.
I also figure out how to adjust the label to how I want them to be, especially those for locations.
Though it is disruptive when I want to print certain labels for which I need multiple copies.

### Suggested solution

As far as I can see there are two possible solutions:

1. allow setting the amount of copies directly in the printing dialog.
2. allow setting the number of copies on a label definition.

Both would be cool.

I am not a Python pro nor you can call me a beginner, I can read the code a little and I found that the labels have a input box for "plugin metadata", so for me a simple approch to solve my second suggestion would be to use that and pass a number of copies to the plugin. But I have no idea how to access those values from a plugin, maybe if someone can point me to a sample.
As far as I can see the brother_ql lib does not support printing copies so my simple solution would be to loop the "send" command for the number of copies passed form the metadata of a label.
This would be totally enough for me, as I am going to design labels for every use case because they are different in size and information so the number I want to have is also fixed for most of them. And if not I would have to create just a copy and name the label also by the numbers of copies the template prints.

### Describe alternatives you've considered

Printing labels not with the Brother plugin but generate the PDF and print that but this results in a slightly different look and size and also uses too many clicks to be a productive solution.

### Do you want to develop this?

- [X] I want to develop this.

**Comment by SchrodingersGat** [comment]
@Alex9779 check out the PR in https://github.com/inventree/inventree-brother-plugin/pull/31 - comments welcome :)
