### ISSUE TITLE
ugettext_lazy was deprecated in Django 3.0 and now removed

### ISSUE THREAD

**Issue by stoklund** [inventree/inventree-brother-plugin#33]
Trying to import this plugin into an InvenTree server running on Django 4.2.10, I see this error:

```
cannot import name 'ugettext_lazy' from 'django.utils.translation' (/var/lib/inventree/venv/lib/python3.11/site-packages/django/utils/translation/__init__.py)
```

Apparently, this function was [deprecated in Django 3.0](https://docs.djangoproject.com/en/3.0/releases/3.0/#features-deprecated-in-3-0), and now it's been removed.

**Comment by SchrodingersGat** [comment]
@stoklund thanks for reporting - fix incoming in https://github.com/inventree/inventree-brother-plugin/pull/34
