### ISSUE TITLE
Printing multiple labels are not in order and sometimes get corrupted

### ISSUE THREAD

**Issue by timmyhadwen** [inventree/inventree-brother-plugin#38]
When printing labels they do not come out in order and sometimes the labels show as just grey print over the entire label (which seems to consume multiple labels from the queue).

**Comment by SchrodingersGat** [comment]
@timmyhadwen you might have to collect some further data about the issues and determine a pattern.

When you say they are "out of order" - is there any sort of consistent pattern that does appear?

With regard to the "grey labels" - do they appear randomly?

I do not currently have access to any hardware to test on, I'm afraid.

**Comment by timmyhadwen** [comment]
Closing this as it seems to be resolved. I believe our printer needed the compression setting switched on.
