### ISSUE TITLE
"Label printing failed" - how to debug further?

### ISSUE THREAD

**Issue by simonkuehling** [inventree/inventree-brother-plugin#4]
Hi @SchrodingersGat 

I am running the development docker server for now - the plugin installed fine there and is available in inventree now.
When trying to print a label I get a `Label printing failed` notification and am wondering how to best debug here...?

My label printer configuration in the plugin:
```
Printer Model: QL-720NW
Label Media: 62
IP Address: 192.168.178.6
Auto Cut: True
```

I verified `brother_ql` is working from inside the docker container with my printer and the same configuration as in inventree:
```
(env) bash-5.1# brother_ql -b network -m QL-720NW -p tcp://192.168.178.6 print -l 62 ../static/img/inventree.png 
WARNING:brother_ql.conversion:Need to resize the image...
INFO:brother_ql.backends.helpers:Sending instructions to the printer. Total: 64972 bytes.
```

This is an excerpt from the logs:
```
inventree-dev-proxy     | 192.168.178.155 - - [13/Apr/2022:09:54:45 +0000] "GET /api/label/part/1/print/?parts[]=1&plugin=brother HTTP/1.1" 200 46 "http://192.168.178.137/part/1/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0" "-"
inventree-dev-server    | [13/Apr/2022 09:54:45] "GET /api/label/part/1/print/?parts[]=1&plugin=brother HTTP/1.0" 200 46
inventree-dev-worker    | 09:54:45 [Q] INFO Process-1:2 processing [edward-table-utah-chicken]
inventree-dev-worker    | Plugin 'brother' is printing a label
inventree-dev-worker    | Label printing failed: Sending notification to user 'admin'
inventree-dev-proxy     | 192.168.178.155 - - [13/Apr/2022:09:54:46 +0000] "GET /api/notifications/?read=false HTTP/1.1" 200 2 "http://192.168.178.137/part/1/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0" "-"
inventree-dev-server    | [13/Apr/2022 09:54:46] "GET /api/notifications/?read=false HTTP/1.0" 200 2
inventree-dev-worker    | /home/inventree/dev/env/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1358: RuntimeWarning: DateTimeField NotificationEntry.updated received a naive datetime (2022-04-12 00:00:00) while time zone support is active.
inventree-dev-worker    |   warnings.warn("DateTimeField %s.%s received a naive datetime "
inventree-dev-worker    | Gathering users for notification 'label.printing_failed'
inventree-dev-worker    | Sending notification 'label.printing_failed' for 'Brother - brother'
inventree-dev-worker    | Triggering method 'ui_message'
inventree-dev-worker    | Notify users via 'ui_message' for notification 'label.printing_failed' for 'Brother - brother'
inventree-dev-worker    | 09:54:47 [Q] INFO Enqueued 178
inventree-dev-worker    | Notified 1 users via 'ui_message' for notification 'label.printing_failed' for 'Brother - brother' successfully
```

**Comment by simonkuehling** [comment]
The notification says `'length'` as the message body - haven't figured out where that comes from... 

![Bildschirmfoto vom 2022-04-13 13-10-32](https://user-images.githubusercontent.com/296454/163167994-63941836-e358-482b-a3be-c4910fcaec65.png)

So far I verified that the `label_image` object is supplied correctly by saving it as a PNG and manually printing through `brother_ql`:
```
    def print_label(self, label_image, **kwargs):
        """
        Send the label to the printer
        """
        label_image.save("/home/inventree/debuglabel.png")
[...]
```

**Comment by SchrodingersGat** [comment]
And what configuration do you have for the plugin:

![image](https://user-images.githubusercontent.com/10080325/163170944-d35d9d33-f3ba-4c19-a705-dbd6b79249cb.png)

**Comment by SchrodingersGat** [comment]
![image](https://user-images.githubusercontent.com/10080325/163171108-93bc1e70-fcfe-473f-b9fa-6a016d19d66e.png)

Maybe the error is coming from here: 

```python
length = kwargs['length']
```

Can you print out the `**kwargs` which are supplied to the `print_label` function?

**Comment by SchrodingersGat** [comment]
FYI I am now getting the exact same error message on my end, investigating now.

**Comment by simonkuehling** [comment]
Here is my settings:

![Bildschirmfoto vom 2022-04-13 13-33-46](https://user-images.githubusercontent.com/296454/163172043-193c9aa5-e062-4ca2-bdc7-77c9709b8a08.png)

And this is the `kwargs` variable from inside `print_label()`:

```
inventree-dev-worker    | Plugin 'brother' is printing a label
inventree-dev-worker    | {'width': 70.0, 'height': 24.0}
inventree-dev-worker    | Label printing failed: Sending notification to user 'admin'
```

Does `BrotherQLRaster` do automatic resizing like if `brother_ql print` is run from command line?

**Comment by simonkuehling** [comment]
Oh, this is probably why - we are reading `length` and `width` here, but the array has `height` and `width` as its keys:

```
        # Extract length and width information
        length = kwargs['length']
        width = kwargs['width']
```

```
{'width': 70.0, 'height': 24.0}
```

**Comment by SchrodingersGat** [comment]
Yep, fix incoming :) not sure how I didn't see this in my testing previously!

**Comment by SchrodingersGat** [comment]
Please install latest version and check again :)

**Comment by simonkuehling** [comment]
amazing! It is printing now :-)

I now see a new topic - but I will open another issue for that in a second..
