### ISSUE TITLE
Can only print labels with admin account.

### ISSUE THREAD

**Issue by akrly** [inventree/inventree-brother-plugin#45]
Hi,

I am setting up Inventree at my company So far so good. I really love the system, but I ran into a problem. We have a QL-820NWbc printer and I can print labels with it just fine with the default "admin" account. However, I get the following error when I try to print with another user:

![Image](https://github.com/user-attachments/assets/52367638-7e5a-4f38-95bf-10b053d9528c)

I tried the following already:
- Set admin and superuser privilege
- Create new users
- Creating labels with the built-in pdf plugin (this was always a success)

I am running a Docker install. Let me know if I need to provide further details.

Attila

**Comment by SchrodingersGat** [comment]
@akrly interesting.. Can you please provide full version information for your installation?

**Comment by akrly** [comment]
# Version Information:
InvenTree-Version: 0.15.7
Django Version: 4.2.14
Commit Hash: 0d8eb2e
Commit Date: 2024-07-27

Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-6.1.0-21-amd64-x86_64-with
Installer: DOC

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.0.0'}, {'name': 'InvenTreeLabelMachine', 'slug': 'inventreelabelmachine', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}, {'name': 'Brother Labels', 'slug': 'brother', 'version': '0.9.0'}]


![Image](https://github.com/user-attachments/assets/a0196377-cfad-4bdf-bf89-9a1d8d95190f)

**Comment by SchrodingersGat** [comment]
And the "admin" account is always successful, even when you are trying to print the exact same label items?

**Comment by SchrodingersGat** [comment]
> However, I am still curious what could be behind the error. Could it be a networking issue? The printer is wired to our network and the docker is running on a VM in-house on the same network.

I think that because it is reporting a `404` it is likely that the ID of the item you tried to print did not match a valid item in the database.

Note that in later versions of InvenTree the entire printing framework has been updated and refactored - and I am pretty sure this issue has subsequently been resolved.

Glad you got it working!
