### ISSUE TITLE
Configuration missing from normal UI

### ISSUE THREAD

**Issue by sur5r** [inventree/inventree-brother-plugin#49]
There's no "Admin Center" in the normal UI. Due to GHSA-2crp-q9pc-457j, I can't use PUI.
How can I make the configuration show up in the normal UI?

**Comment by matmair** [comment]
You can not, it is only in PUI

**Comment by matmair** [comment]
Also that was patched in the 0.16.x release series. How is this stopping you from using PUI?

**Comment by sur5r** [comment]
I'm on current master (327884ca2691887b4c034deb921eaee3abd28b97) and the login request from PUI results in a 403 response:

```json
{"detail":"MFA required for this user"}
```

**Comment by sur5r** [comment]
Ah, it seems I can manually go to `/platform` after being logged it. I didn't expect that to work. So that's a workaround for the broken PUI-MFA-Login I guess.
