### ISSUE TITLE
[FR] I think we need a config for rotation

### ISSUE THREAD

**Issue by simonkuehling** [inventree/inventree-brother-plugin#6]
@SchrodingersGat, using a QL-720NW label printer with 62mm endless tape, I realize that we would probably need to make image rotation a config option in the plugin settings... Do you agree?

This looks a little excessive as it is *g

![22-04-13 13-58-53 3584](https://user-images.githubusercontent.com/296454/163175361-0e939724-f218-4080-b922-ced92e74e025.jpg)

**Comment by SchrodingersGat** [comment]
Yeah, for sure it should be an option. Feel free to submit a PR, the addition of the new option would be very simple if you just follow the existing code!

**Comment by simonkuehling** [comment]
happy to do so :+1:

**Comment by matmair** [comment]
This was closed with #6

**Comment by simonkuehling** [comment]
Sure - closing this.

**Comment by matmair** [comment]
@simonkuehling thx and thank you for the PR. We are not very used to users also submitting what they wont programmed from us ;-)

**Comment by simonkuehling** [comment]
Its a real pleasure to see a project documented and structured as well as this - so that it is even possible to start contributing as fast in the first place… well done!

**Comment by matmair** [comment]
@simonkuehling glad to hear that!
If you want to change anything or have an idea for additional features do not hesitate to ping @SchrodingersGat (maintainer) or me. We are always happy to engage!

**Comment by SchrodingersGat** [comment]
Thanks again for the contribution too, @simonkuehling - I'm glad that you were able to get it working :)
